name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Node.js project
        run: npm run build-tsc

      - name: Display structure of downloaded files
        run: ls -R

      - name: Archive dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v1

      - name: Download dist folder
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Display structure of downloaded files
        run: ls -la
      - name: Display structure
        run: ls -la /home/runner/work/jira-metrics-exporter/jira-metrics-exporter

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name:latest .
        #   docker push your-docker-image-name:latest
        # env:
        #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
